name: Calibre News Delivery
run-name: 'Calibre News Delivery: ${{ github.ref_name }}'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' 

permissions:
  contents: read

jobs:
  worker:
    runs-on: ubuntu-latest
    environment: calibre-news
    env:
      output: converted_ebooks
      publisher: bookfere.com
      author: Calibre News Delivery
      ext: ${{ secrets.FORMAT || 'epub' }}
      size: ${{ secrets.SIZE || 25 }}
      # Google Drive settings
      DRIVE_FOLDER_ID: ${{ secrets.DRIVE_FOLDER_ID }}  # Replace with your Google Drive folder ID
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }} 

    steps:
      # ... (previous steps remain the same) ...

      - name: Install gdrive
        if: ${{ success() }}
        run: |
          sudo apt-get install -y wget
          wget -qO- 'https://raw.githubusercontent.com/prasmussen/gdrive/master/scripts/gdrive' | sudo tee /usr/local/bin/gdrive > /dev/null
          sudo chmod +x /usr/local/bin/gdrive

      - name: Authenticate gdrive
        if: ${{ success() }}
        run: |
          echo $CLIENT_ID $CLIENT_SECRET > client_secrets.json
          gdrive about --refresh-token $REFRESH_TOKEN

      - name: Upload to Google Drive
        if: ${{ success() }}
        run: |
          while read -d '' ebook_path; do
            filename="$(basename "$ebook_path")"
            title="${filename%.*}"
            file_size=$(du -m "$ebook_path" | cut -f 1)
            if [ $file_size -ge $size ]; then
              echo "Size exceeds the limitation: $filename (${file_size}MB)"
              continue
            fi
            echo "Uploading: \"$filename\""
            gdrive upload --parent $DRIVE_FOLDER_ID "$ebook_path"
          done < <(find "$output" -type f -name "*.${ext,,}" -print0)
          echo "All jobs done"

      - name: Storing Ebook
        if: ${{ success() }}
        uses: actions/upload-artifact@v4
        with:
          name: Calibre-News-Delivery
          path: ${{ env.output }}
          retention-days: ${{ secrets.DAYS || 90 }}